### PR TITLE
adds instructions for people getting started

### PR DESCRIPTION
**Pull request by stweise**
- adds instructions for people getting started
- fixes exclude on convertImages.sh
- tries to work around xxd -i -n used by original author which is not available on linux (Author has some nicer BSD xxd variant)

### CODE REVIEW

**Comment by Michal-Szczepaniak** [comment]
xxd -i -n does exis on linux, freely available on opensuse for example hell it even exists on my phone which uses sailfishos

**Comment by Michal-Szczepaniak** [comment]
Why close it?

**Comment by atsidaev** [comment]
Good manual btw. As a new watchy user without platformio experience I faced literally every problem it covers: no freetype, no imagemagick (since generate.sh does not fail on errors it's easy to overlook these issues), had no idea how to upload the compiled binary... Would be great if this is merged.

**Comment by Michal-Szczepaniak** [comment]
@atsidaev for some reason author closed the PR so i'm not sure it would be legal for me to just copy paste them

**Comment by atsidaev** [comment]
> @atsidaev for some reason author closed the PR so i'm not sure it would be legal for me to just copy paste them

Technically, author's repo is still available and according to its README.md and COPYING it's still under GPLv3 - so incorporating its parts into any other GPLv3 project is legal, I suppose

**Pull request closed without merging**
